version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/EmuFish.Core/"
    schedule: 
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/EmuFish/"
    schedule: 
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/EmuFish.SharkBoy/"
    schedule: 
      interval: "daily"
