name: Main

on: [push, pull_request]

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Install .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '5.0.202'
  build:
    needs: [setup]
    runs-on: windows-latest
    strategy:
      matrix:
        target: [win-x64, linux-x64, linux-arm64, osx-x64]
        self-contained: [self-contained, framework-dependent]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Install .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '5.0.202'
      - name: Build
        run: dotnet publish -r ${{matrix.target}} --self-contained ${{ matrix.self-contained == 'self-contained' }}
      - name: Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: emufish-${{matrix.target}}-${{matrix.self-contained}}
          path: |
            EmuFish/bin/Debug/net5.0/${{matrix.target}}/publish/
