name: Main

'on':
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - win-x64
          - linux-x64
          - linux-arm64
          - osx-x64
          - osx-arm64
        self-contained:
          - self-contained
          - framework-dependent
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: Install .NET
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: >-
          dotnet publish -r ${{matrix.target}} --self-contained ${{
          matrix.self-contained == 'self-contained' }}
      - name: Package
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'emufish-${{matrix.target}}-${{matrix.self-contained}}'
          path: |
            EmuFish/bin/Debug/net6.0/${{matrix.target}}/publish/
