name: Main

'on':
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - win-x64
          - linux-x64
          - linux-arm64
          - osx-x64
          - osx-arm64
        self-contained:
          - self-contained
          - framework-dependent
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: Install .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Install NetBeauty
        run: >-
          dotnet tool install --global nulastudio.nbeauty --version 2.0.0-beta.1
        if: ${{ !startsWith(matrix.target, 'osx-') }}
      - name: Restore
        run: >-
          dotnet restore -r ${{matrix.target}}
      - name: Build
        run: >-
          dotnet ${{ startsWith(matrix.target, 'osx-') &&
            'msbuild -t:BundleApp' ||
            'publish'
          }} ${{ startsWith(matrix.target, 'osx-') &&
            '-p:RuntimeIdentifier=${{ matrix.target }}' ||
            '-r ${{ matrix.target }}'
          }} ${{ startsWith(matrix.target, 'osx-') &&
            format('-p:SelfContained={0}', matrix.self-contained == 'self-contained') ||
            format('--self-contained {0}', matrix.self-contained == 'self-contained')
          }}
      - name: Beautify
        run: >-
          nbeauty2 --loglevel Info EmuFish/bin/Debug/net6.0/${{matrix.target}}/publish Lib
        if: ${{ !startsWith(matrix.target, 'osx-') }}
      - name: Archive
        run: >-
          ${{ startsWith(matrix.target, 'win-') &&
            'zip -9 EmuFish.zip EmuFish/bin/Debug/net6.0/${{ matrix.target }}/publish' ||
            format('tar cvf - EmuFish/bin/Debug/net6.0/${{matrix.target}}/publish{0} | gzip -9 - > EmuFish.tar.gz',
              startsWith(matrix.target, 'osx-') && '/EmuFish.app' || '') }}
      - name: Package
        uses: actions/upload-artifact@v3.0.0
        with:
          name: 'emufish-${{matrix.target}}-${{matrix.self-contained}}'
          path: EmuFish${{ startsWith(matrix.target, 'win-') && '.zip' || '.tar.gz' }}
