name: Main

'on':
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - win-x64
          - linux-x64
          - linux-arm64
          - osx-x64
          - osx-arm64
        self-contained:
          - self-contained
          - framework-dependent
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: Install .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: >-
          dotnet restore -r ${{ matrix.target }} -p:BeautyEnable=${{ !startsWith(matrix.target, 'osx-') }} 
      - name: Build
        run: >-
          dotnet ${{ startsWith(matrix.target, 'osx-') &&
            'msbuild EmuFish/EmuFish.fsproj -t:BundleApp' ||
            'publish EmuFish/EmuFish.fsproj'
          }} ${{ startsWith(matrix.target, 'osx-') &&
            format('-p:RuntimeIdentifier={0}', matrix.target) ||
            format('-r {0}', matrix.target)
          }} ${{ startsWith(matrix.target, 'osx-') &&
            format('-p:SelfContained={0}', matrix.self-contained == 'self-contained') ||
            format('--self-contained {0}', matrix.self-contained == 'self-contained')
          }} -p:BeautyEnable=${{ !startsWith(matrix.target, 'osx-') }}
      - name: Archive
        run: >-
          ${{ startsWith(matrix.target, 'win-') &&
            format('pushd EmuFish/bin/Debug/net6.0/{0}/publish; zip -9 -r ../../../../../../EmuFish.zip .; popd', matrix.target) ||
            format('tar cvf - EmuFish/bin/Debug/net6.0/{0}/publish{1} -C EmuFish/bin/Debug/net6.0/{0}/publish | gzip -9 - > EmuFish.tar.gz',
              matrix.target,
              startsWith(matrix.target, 'osx-') && '/EmuFish.app' || '') }}
      - name: Package
        uses: actions/upload-artifact@v3.0.0
        with:
          name: 'emufish-${{matrix.target}}-${{matrix.self-contained}}'
          path: EmuFish${{ startsWith(matrix.target, 'win-') && '.zip' || '.tar.gz' }}
